### ISSUE TITLE
Add @mixin PageType for corresponding PageType_Controller

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#1]

**Comment by Zauberfisch** [comment]
more importantly, also add:


    /**
     * @property FooPage dataRecord
     * @method FooPage data
     */
    class FooPage_Controller extends Page_Controller {

**Comment by axyr** [comment]
I need to try it, but I think providing @mixin FooPage will expose all methods from FooPage in the Controller?

**Comment by Zauberfisch** [comment]
yes, but not to `$this->data()` or `$this->dataRecord`, and calling `$this->Foo` is actually "mapped" to `$this->data()->Foo`.
I personally am a friend of explicitly calling methods on the model if I know they are on the model, so I would always use `$this->data()->Foo` rather than `$this->Foo`

**Comment by Firesphere** [comment]
This sounds hard to detect, because it's not always Page_Controller that's being extended, nor does everyone explicitly us the class FooPage_Controller.

**Comment by Firesphere** [comment]
Hmmm, maybe explode the files on the class declarations.... Add the docblocks, then implode? It's archaic, but might work?

**Comment by axyr** [comment]
@Firesphere 
can you review this : 

https://github.com/axyr/silverstripe-ideannotator/blob/c3904c225f35d0f62512feff93f0c7d257d514fe/tests/ControllerAnnotatorTest.php

Aside from the duplication in the code that needs to be cleaned up, do you miss any tags that need to be added to ContentControllers and Extensions ?

**Comment by Firesphere** [comment]
Reviewed and agreed. No issues found that would be a blocker. Closing this issue. Please refer to #55 for the last bit of problems before release 2.0
