### ISSUE TITLE
private or protected?

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#13]
Shouldn't the protected functions be private?

**Comment by axyr** [comment]
Maybe...
I made them protected to keep the public API as small as possible.
I did not made them private so I could test the method seperatly by extending class for UnitTests:

https://github.com/axyr/silverstripe-ideannotator/blob/master/tests/DataObjectAnnotatorTest.php#L163
Maybe not the way to go, but it works :)

**Comment by Firesphere** [comment]
You can easily mock privates, So it shouldn't be a blocking?

**Comment by axyr** [comment]
I think this is a minor... closed for now...
