### ISSUE TITLE
StartGeneratedWithDataObjectAnnotator

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#14]
I think the opening/closing tag should be a bit shorter?

**Comment by Zauberfisch** [comment]
or configureable via yml

**Comment by axyr** [comment]
Yeah, maybe... but this involves some code to support backwards compatibilty..
If we  rename the Start and End tags as well I guess, which will create cuplicate code blocks..
I don't have time for that at the moment..

**Comment by markguinn** [comment]
+1 for configurable via YML. I don't think you need backwards compatibility then do you? One could just do a project-wide find/replace as long as the default is what it currently is and the procedure for changing them is documented. I'm happy to work up a PR for that if you want.

**Comment by Firesphere** [comment]
I'm slightly lacking time to work on this, @markguinn, if you have the time, please do. I guess a protected value is enough to set defaults which fixes the backward compatibility, since I doubt it's something that will change often.

**Comment by axyr** [comment]
This commit makes StartWith/EndWith markers obsolete :
beffcca6ca255955c302a4c77c89e34977f26698

Existing StartWith/EndWith markers will be removed on next build.

**Comment by Firesphere** [comment]
Nice one! Looks much better this way.
Looks stable as well.
