### ISSUE TITLE
DataObjectAnnotator?

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#18]
Shouldn't the classes be "IDEAnnotator", after the repo-name? Makes more sense.

**Comment by axyr** [comment]
Yeah, maybe... but this involves some code to support backwards compatibilty..
We should rename the Start and End tags as well I guess, which will create cuplicate code blocks..
I don't have time for that at the moment..

**Comment by axyr** [comment]
Not sure. 
I think if we create also Page_Controller we might put that in a seperate class besides the DataObjectAnotator.

We could then create a IDEAnnotator as a wrapper class to call all the seperate Annotator classes?

**Comment by Firesphere** [comment]
That actually sounds like a better plan than what I've been looking at to implement. My explode-method in the other issue is terrible in hindsight! :+1:
