### ISSUE TITLE
Fix compatibility with namespaces

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#28]
Currently, namespaces are not supported, this might cause issues later.

**Comment by axyr** [comment]
I think we should NameSpace the whole module.
Maybe after I implemented phpDocumentor

**Comment by Firesphere** [comment]
I'm getting issues with phpDocumentor. I keep getting undefined or not found errors. Any idea?

**Comment by axyr** [comment]
Undefined what?

**Comment by Firesphere** [comment]
It's not entirely related, but somehow, for me locally, I can not get phpDocumentor to be recognized. It's kinda weird actually. Install simply fails to recognize the vendor installation.

**Comment by axyr** [comment]
All vendor files or just phpdocumentor?

**Comment by Firesphere** [comment]
It's specifically phpDocumentor not being recognised. It's really weird though. And it's only locally.

**Comment by axyr** [comment]
I know I don't need to suggest it, but does rm -rf your cache dir (also for cli, if the error occurs there) helps?

**Comment by axyr** [comment]
What do you think: should we add all classes in a NameSpace with exception of the Annotable class?
That is the only one that gets 'connected' with Silverstripe.
Would this work with Config settings?

**Comment by Firesphere** [comment]
Right now, just namespacing everything but the annotate extensions itself, _should_ work fine and Config works as long as namespaced items that are needed in the yml, are fully specified with the full namespace.

In the future, Everything should be fully namespaced. But let's await SS4 first, before jumping to conclusions that'll bite back.

**Comment by axyr** [comment]
ok, i will close this. we will see for ss4 later

**Comment by Firesphere** [comment]
Very much agreed.
