### ISSUE TITLE
Try to detect existing docblocks

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#3]
Now, if the dockbloc is already existing before installing, it's made again instead of being updated.

**Comment by axyr** [comment]
Yes it will generate anyway if there is no StartGeneratedWithDataObjectAnnotator and no EndGeneratedWithDataObjectAnnotator in the file. 
I did this, to allow undo actions by checking for the presence of these tags.
And undo action might indeed not necessary...

We could check if an annotation already exists foreach property or method, but this requires some better docblock matching...

But if the only annotations present are coming from the generator, this is not a problem...

**Comment by axyr** [comment]
I think this is what I will pull in : 
https://github.com/phpDocumentor/ReflectionDocBlock

**Comment by Firesphere** [comment]
That looks promising.
