### ISSUE TITLE
Implemented GitFlow

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#35]
I've started using the GitFlow method on this module. Sorry if it causes any confusion.
dev-master or a version tag is _always_ stable!

**Comment by Firesphere** [comment]
Preferably use `feature/featurename`, not `feature-featurename`, in line with GitFlow.

For those unfamiliar with GitFlow, you can read more here. Also, SourceTreeApp has the ability to use GitFlow built in.
https://danielkummer.github.io/git-flow-cheatsheet/

**Comment by axyr** [comment]
will fix it later on.
and rename the feature to phpDocumentor..
