### ISSUE TITLE
Generate metadata for factory method auto completion

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#36]
Currently methods like TextField::create(); does not 'resolve' to the TextField class but stays in Object.

Laravel as a great ide helper:
https://github.com/barryvdh/laravel-ide-helper
which generates a same kind of helper file.

PHPStorm documentation
https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata

I looked into this, but it is not as easy as it seems.

The problem is that Object::create(); uses get_called_class(); to get the class to generate.
If any has an idea to tackle this, I think this would be a great feature..

**Comment by axyr** [comment]
Edited title to not only support phpstorm...

**Comment by Firesphere** [comment]
Wouldn't this be more of something for the SSTemplate module, than in here?

**Comment by axyr** [comment]
Well. It bothers me and the purpose of this module is to support autocompletion. At least thats why I created this module...

So think it fits fine in here and once figured out how to map ClassName::create(); to ClassName the generation of the file should be fairly easy...

**Comment by axyr** [comment]
If we only had namespaces already... it would be much easier...

**Comment by Firesphere** [comment]
Valid point :)

**Comment by Firesphere** [comment]
I just tried one very risky method. Just because.

It's parsing the file, and prepends every `${something} = {ObjectThing}::create()` with `/** @var ObjectThing $something */` To my surprise, it actually didn't destroy anything, but I am also very strongly AGAINST implementing something like this. It was a trial to see if the parsing of the file is possible ;)

**Comment by axyr** [comment]
I noticed that NetBeans has no problem with methods like TextField::create(...)->getMaxlength();

I use the /** @var .. */ etc as well, but it is pretty noisy if you ask me.

And for Form I never assign the Fields to a variable. Forms is where I have the most mess in PHPStorm...

I guess we should forget this for this module..

Or we need namespaces in SS or we need a PHPStorm build-in/plugin solution. Which I unfortunately do now know how to code...

**Comment by Firesphere** [comment]
Well, namespacing will be done in 4, hopefully. But yeah, for PHPStorm, I think we'll have to fall back on the SilverStripe plugin.

**Comment by axyr** [comment]
Which only supports the template language...

**Comment by Firesphere** [comment]
It actually does more, but was never renamed I think.

**Comment by axyr** [comment]
By not using create all the time, but just plain 'new ClassName', this is not a big problem...

I use create for all my forms, which makes them pretty ugly.

No, I favor code like this : 

```php
new FieldGroup(
    (new LimitedTextField('Zip', _t('Site.Zipcode', 'Zipcode')))
        ->addExtraClass('geocode'),
    (new LimitedTextField('City', _t('Site.City', 'City')))
        ->addExtraClass('geocode toggle')
)
```
Any reason why I 'should' use SomeClass::create instead?

**Comment by Firesphere** [comment]
Because create uses the Injector, which can return a spec faster. But that's all there is to it.

**Comment by Firesphere** [comment]
I still think though, supporting ::create() would be awesome.
But it's a minor issue and I would not think, it's part of what this module is trying to achieve.

**Comment by wernerkrauss** [comment]
FY(and others)I: the phpstorm plugin now manages ::create() autocompletion. See https://github.com/raket/idea-silverstripe/issues/66

**Comment by axyr** [comment]
Thanks :)

Closed : use this https://github.com/raket/idea-silverstripe
