### ISSUE TITLE
@property annotations are missing '$'; causes NetBeans to ignore the annotations

### ISSUE THREAD

**Issue by oddnoc** [axyr/silverstripe-ideannotator#37]
NetBeans doesn't recognize the @property annotations, because the name lacks the leading '$'. So `@property string Question` does *not* work, but `@property string $Question` *does* work. This is also as documented in the [PHPDocumentor documentation](https://manual.phpdoc.org/HTMLSmartyConverter/PHP/phpDocumentor/tutorial_tags.property.pkg.html).

**Comment by Firesphere** [comment]
Indeed. It also seems methods should be `@method Class Method()`, according to the docs.

**Comment by Firesphere** [comment]
Feel free to create a PR if you have the time?

**Comment by Firesphere** [comment]
Resolved. Let us know if version 1.0.2 works better for you?

**Comment by oddnoc** [comment]
Works great, thanks!

**Comment by Firesphere** [comment]
Happy to be of service :)
