### ISSUE TITLE
Autocompletion broke for assert calls in Tests

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#44]
see : 
https://github.com/axyr/silverstripe-ideannotator/blob/master/tests/DataObjectAnnotatorTest.php#L9

This breaks auto completion of the assert methods in PHPStorm.

Why did you add this tags?

**Comment by Firesphere** [comment]
Ehh, huh? Ok, that's a serious bad on my side.

Without the mixin, the IDE doesn't recognise them. I added them without thinking it through.

It shouldn't break the auto-completion, but if it does, feel free to remove them of course. It's probably something on my side with settings.
