### ISSUE TITLE
DB alteration message should only show when something is changed

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#46]
Really minor, but I guess it would be nice if it only shows up in dev/build when actually changed a file.

Leave it for now, and check this when phpDocumentor is used.

**Comment by Firesphere** [comment]
Agreed. I think this should be based on the return value? True would mean annotated, false would mean error, 'updated annotations' or something would mean success?
We can't blindly use true/false in this case, I think.

**Comment by axyr** [comment]
Moved the message in 33bae62f503f3f2b96ad09bc68919d2d7ea061f2 call, so it is only trigged when there is a difference
