### ISSUE TITLE
Add .ignoreannotations file support.

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#50]
For if you don't want a directory to be annotated (for example, the annotators test-DO's), adding a file named .ignoreannotations (or something alike) should make sure that all DO's in that folder and it's subfolders are skipped for annotations.

**Comment by axyr** [comment]
Implementers of TestOnly are ignored?

**Comment by Firesphere** [comment]
I'm not sure if it's needed. It was something mentioned to me last week and I can see it might be useful, thus I figured, why not add it to the issue list. Very low priority if you ask me though.

**Comment by axyr** [comment]
Besides test classes, I can't see a use case that one wants to annotate mysite or another folder but skip 1 DataObject? Whats the point then to having ideannotator generating docblocks at all?

**Comment by axyr** [comment]
I close this for now.
If it is really important, it will pop up again...
