### ISSUE TITLE
allow generation of modules without dataobjects

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#54]
a module with only extensions will not be generated...

**Comment by Firesphere** [comment]
This will require a very ugly hack, because there's no good way to determine all the subclasses of DataExtension, besides this method:
```
$classes = array();

foreach( get_declared_classes() as $class ) {
    if ( is_subclass_of($class, 'DataExtension') ){
        array_push($classes, $class);
    }
}
```
Which basically means looping all registered classes. Just to capture the few that are allowed to be run.

**Comment by axyr** [comment]
unless we scan dirs for allowed modules instead of getting all classes and then check if they are located in an allowed module

**Comment by Firesphere** [comment]
Hmmm, that might actually work! Hadn't thought of that.

**Comment by axyr** [comment]
It does already work when running : 

dev/tasks/DataObjectAnnotatorTask?module=mymodule

I never actually use that task, but I will document it.

**Comment by Firesphere** [comment]
It's actually somewhat funny you made an issue for something that already exists and works :D
