### ISSUE TITLE
Master seems to no more removed unused properties

### ISSUE THREAD

**Issue by anselmdk** [axyr/silverstripe-ideannotator#55]
I updated to the master version yesterday, and I really appreciate how things work without needing to add the start and end tags, however it seems that unused properties are no more removed.
See below - I removed `ReadMoreTitle` and `Content`, but after a db build they are still there

```php
<?php

/**
 * ReadMoreBlock
 *
 * @author Anselm Christophersen <ac@anselm.dk>
 * @date April 2016
 * @property string $Summary
 * @property string $Content
 * @property string $ReadMoreTitle
 * @property int $ImageID
 * @method Image Image()
 * @property int $LinkID
 * @method Link Link()
 */
class ReadMoreBlock extends Block
{
    private static $singular_name = 'Read More';
    private static $plural_name = 'Read More';

    private static $db = [
        'Summary' => 'Text',
    ];

    private static $has_one = [
        'Image' => 'Image',
        'Link' => 'Link',
    ];
}
```

**Comment by Firesphere** [comment]
Although it shouldn't show this behaviour, I can confirm this is the case.
It seems the existing, generated and the new docblocks are correctly merged, but the removed items aren't correctly unset.
This needs to be fixed before milestone 2.0. @axyr do you have time to have a look at this? For some reason, I can't get my debugger to work anymore, so I'm struggling to even get any data about what's going wrong.
I've updated develop to match Master, please try to fix on Develop and then merge to master. If I find what's wrong, I'll push a patch for review.

**Comment by axyr** [comment]
Nice find!
Will take a look today.

**Comment by Firesphere** [comment]
A rough guess, is that a simple array-compare and purge the not-found items in property/method/mixin etc. from the original will do the job.
But that's a rough guess after a quick look what's going wrong.

**Comment by axyr** [comment]
I know what is happening.

At the moment the generator keeps all existing tags, in case someone has added their own tags other then the module provides. (like in the example of @anselmdk with @author, @date) 

In this way you can always change your docblocks manually and still run the generation of tags without the need of the old StartWith/EndWith markers.

The only way to remove obsolete tags is to NOT keep existing $property, $method and @mixin tags.

What do you think?

**Comment by Firesphere** [comment]
Save the property/method/mixin tags to a backup-array for when everything fails. When running the annotations, check if any of the properties are gone in the new run and delete those I'd say.

It does say in the readme that we actively alter your files...

**Comment by Firesphere** [comment]
We should update the tests to cover this scenario. I'll have a look if I can make the tests fail for this scenario?

**Comment by anselmdk** [comment]
I agree, I'd be happy for the module to completely take over `@property`, `@method` and `@mixin` tags for me.
Maybe - for the case that somebody really wants custom versions of these tags - we could have some special `startCustom`/ `endCustom` lines, just the way this module used to have before? I'd assume that this will be needed for very special cases only.

**Comment by Firesphere** [comment]
It would be a very, very, very edge-case scenario. Which I think is covered by the warning that the file contents are actively changed?

**Comment by axyr** [comment]
I will skip the `@property`, `@method` and `@mixin` tags in the merge existing comparison

**Comment by Firesphere** [comment]
Sounds like the best way to go. Comparing would be a pain and how often 
will it happen?

**Comment by Firesphere** [comment]
Almost got the tests done for this change. I'll push them to master (and fail the build, ONOES!) when done.

**Comment by Firesphere** [comment]
Having the system not override existing, different docblocks (like @property Group $group My Awesome description), is something we can add later.

**Comment by Firesphere** [comment]
I've pushed the test if the block doesn't contain the removed item to develop. Expect reds until it's fixed!

**Comment by anselmdk** [comment]
Just reran this, and it works - great work guys!
