### ISSUE TITLE
scutinizer-ci : The method getRequest does only exist in Security, but not in AdminLoginExtension

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#57]
@property Security|AdminLoginExtension $owner

Should we remove the Extension class for $owner ?

see this example : 

https://scrutinizer-ci.com/g/axyr/silverstripe-adminlogin/inspections/45a7bcca-30da-4a33-963c-3483f9b1e14f/issues/files/code/AdminLoginExtension.php?status=new&orderField=path&order=asc&honorSelectedPaths=0

**Comment by Firesphere** [comment]
Since the classname is "somethingsomethingExtension", I don't see why removing it would be a good thing to remove the declaration?

**Comment by axyr** [comment]
Well the extension is not an $owner right? only the class it belongs to...

**Comment by axyr** [comment]
And when you have a method on an Extension and you call it with $this->owner->MethodOnExtension();
Would this not be a round trip from Extension => $owner => Extension ?

**Comment by axyr** [comment]
I have removed it... If you have a good reason to have it, we can bring it back. But I don't see the Extension as an $owner even when its methods are accessible thru $this->owner...
