### ISSUE TITLE
Use ClassInfo::classes_for_file(); to collect classes

### ISSUE THREAD

**Issue by axyr** [axyr/silverstripe-ideannotator#59]
This means : 
- we can have modules without Dataojects to annotate (now only works with the task)
- hook into requireDefaultRecords only once to trigger the generation process..

**Comment by Firesphere** [comment]
If hooking into requireDefaultRecords only once... I'd suggest we switch to flushable, and implement flush() method.
That would mean it's only called at flush. We could check if it's an "all" or "1" option, and only start generation if it's "all".
That would be the cleanest way, and fix the fact that requireDefaultRecords is actually not the cleanest implementation.

**Comment by axyr** [comment]
hm.. I understand what you mean.

But. only on dev/build the database fields are generated and the extensions are coupled..

So triggering on flush would require or a second action or require to always use dev/build?flush=all/1

Or am I wrong about what flush is doing?

**Comment by axyr** [comment]
So in fact we need a MyObject implements DevBuildable ;)

**Comment by Firesphere** [comment]
flush is running on flush=all indeed. So there would be an extra check for if it's in the build process. Still, I'd think it's cleaner.

And yes.. I raised an issue about that on the framework ;)

**Comment by Firesphere** [comment]
There's requireDefaultRecords, Flushable, but _not_ an option to hook into the actual build :'(

**Comment by axyr** [comment]
Note2Self:

just hook into dev/build once and traverse the enabled modules:

https://github.com/silverstripe/silverstripe-framework/blob/3/dev/DevBuildController.php
