### ISSUE TITLE
Extensions need to have themselves set as owner

### ISSUE THREAD

**Issue by Firesphere** [axyr/silverstripe-ideannotator#61]
Currently, all DB records etc., are not recognized. If the extension has `@property owner|extensionname $owner`, they're not seen as magic __get and __set anymore.

**Comment by axyr** [comment]
You have an example? In phpstorm all $db fields are autocompleted...

**Comment by Firesphere** [comment]
I guess I did something wrong. It indeed works now in PHPStorm. Possibly an accidental missing mixin tag or something? I don't know.
In conclusion: Nevermind. Closing.

**Comment by axyr** [comment]
fixed with https://github.com/axyr/silverstripe-ideannotator/commit/c4ca45b3e59a0e9784ce1b5ffab7c317c7082ca7
