### ISSUE TITLE
Provide more feedback if class cannot be annotated

### ISSUE THREAD

**Issue by hailwood** [axyr/silverstripe-ideannotator#62]
We need to be giving more feedback - 
e.g. 
"Could not annotate 'MyDataObjectClass' as it is not writeable"
"Could not find replacement string "class MyDataobjectClass" to prepend annotation"

Currently it's a mission trying to work out why your files are not being annotated.

**Comment by Firesphere** [comment]
Do you have a codesnippet where this is happening? I've never had these problems, except not writable, but that would throw a whole bunch of other errors on the cache to me.

**Comment by hailwood** [comment]
@Firesphere https://github.com/axyr/silverstripe-ideannotator/blob/master/code/Helpers/AnnotateClassInfo.php#L58 stops any errors being displayed as we check if the file is writeable before we trying to annotate it so it just fails silently.

For the second one - I ran into the issue when I had "Class MyDataobjectClass" (uppercase C) as we do a literal string match. of course that's not the only case where it would fail "class  MyDataobjectClass" (double space) etc also have the same effect.

--
As an aside I'm probably going to be flicking several issues your way, I'll likely follow the up with PRs when I get a chance but I don't have time at the moment (tight deadline).

**Comment by axyr** [comment]
we could show A message when a file is not writable.

For the other cases. In not sure if we need to support sloppy coding. We are altering files and dont want to do a lot of guessing on what to replace.

I think we can document that you should run your IDE's code formatter before annotating files..  Would that work for you?

**Comment by hailwood** [comment]
@axyr I'm not suggesting we add a whole pile of guesses as to what we *could* be looking for. I'm suggesting we only look for the correct form, and if that's not found then display a message.

So just an "else" statement here https://github.com/axyr/silverstripe-ideannotator/blob/master/code/DataObjectAnnotator.php#L185

**Comment by hailwood** [comment]
Side question that relates to the same block of code - Isn't the docblock for MyPage going to end up on `MyPage_Controller` with the below code? 

```php

class MyPage_Controller {
}

class MyPage {

}

```

Nowhere in Silverstripes docs does it say anything about the class order, so perhaps we should check for 
"class {$className}{" or 
"class {$className} " rather than just 
"class {$className}"

That's the only point I'd suggest checking for an alternative code style.

**Comment by axyr** [comment]
PhpDocumentor takes care of that. is does not matter how many classes there are in 1 file.

See also this test classes : 

https://github.com/axyr/silverstripe-ideannotator/blob/master/tests/mock/AnnotatorPageTest.php

**Comment by axyr** [comment]
Fixed with https://github.com/axyr/silverstripe-ideannotator/commit/fab89f91e8594dac1125324fb47ab12f3ad121e6 and https://github.com/axyr/silverstripe-ideannotator/commit/c7624d147eb0e3b420048a069f54c842c0e637fd
