### ISSUE TITLE
Option to generate external file instead of modifying existing files

### ISSUE THREAD

**Issue by hailwood** [axyr/silverstripe-ideannotator#63]
This one's an idea I'm floating rather than an issue - 
Thoughts on optionally generating an `idehelper.php` stub file rather than writing directly to the files?

We would make it an optional config flag as it does introduce a few quirks - e.g. All annotated classes will show the "Duplicate class declaration" inspection - but it would work well if you want to generate the annotations for a composer managed package. It could even be set on the enabled_modules and done on a per modules basis

The idea is the same as the laravel-ide-helper so we'd end up with one file that contains a bunch of stubs.

```php
/**
 * Generated Doc Block
 */
class MyDataobject{}

/**
 * Generated Doc Block
 */
class AnotherDataobject{}
```

**Comment by axyr** [comment]
and that will break ctrl + click to go the class..
Why would one want to have its docblocks in a seperate file?

**Comment by Firesphere** [comment]
I can only imagine this being useful when the annotator is used in a Live environment? Which is not a good idea, to put it mildly.

**Comment by axyr** [comment]
It's clearly stated not to do that. And the module wont even work when putting a live site into dev with ?isDev=1 .

The only usecase to introduce an idehelper is to autocomplete SomeObject::create() calls.

**Comment by Firesphere** [comment]
Hey @axyr,
I hope you understood my mild sarcasm about putting it mildly? ;)

**Comment by axyr** [comment]
Ofcourse sweetheart :)
